//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace Questionnaire2.Models
{
    [MetadataType(typeof(AppSettingMetaData))]
    public class AppSetting
    {
        public int AppSettingId { get; set; }

        public string AppSettingName { get; set; }

        public string AppSettingValue { get; set; }
    }
}
