//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatticeItem
    {
        public int ItemId { get; set; }
        public string Step { get; set; }
        public string LatticeLevel { get; set; }
        public string ItemType { get; set; }
        public string DropdownText { get; set; }
        public string ItemName { get; set; }
    }
}
