//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Models.Answer> Answers { get; set; }
        public virtual DbSet<Models.AppSetting> AppSettings { get; set; }
        public virtual DbSet<Models.File> Files { get; set; }
        public virtual DbSet<Models.LatticeItem> LatticeItems { get; set; }
        public virtual DbSet<Models.QCategory> QCategories { get; set; }
        public virtual DbSet<Models.QType> QTypes { get; set; }
        public virtual DbSet<Models.QuestionnaireQCategory> QuestionnaireQCategories { get; set; }
        public virtual DbSet<Models.QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
        public virtual DbSet<Models.Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Models.Question> Questions { get; set; }
        public virtual DbSet<Models.Respons> Responses { get; set; }
        public virtual DbSet<Models.UserLevel> UserLevels { get; set; }
        public virtual DbSet<Models.Verification> Verifications { get; set; }
        public virtual DbSet<Models.ZipCode> ZipCodes { get; set; }
    }
}
