//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCategory
    {
        public QCategory()
        {
            this.QuestionnaireQCategories = new HashSet<QuestionnaireQCategory>();
        }
    
        public int QCategoryId { get; set; }
        public string QCategoryName { get; set; }
        public string Instructions { get; set; }
        public bool Repeatable { get; set; }
        public bool Uploads { get; set; }
    
        public virtual ICollection<QuestionnaireQCategory> QuestionnaireQCategories { get; set; }
    }
}
