//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            this.QuestionnaireQCategories = new HashSet<QuestionnaireQCategory>();
            this.QuestionnaireQuestions = new HashSet<QuestionnaireQuestion>();
        }
    
        public int QuestionnaireId { get; set; }
        public string QuestionnaireName { get; set; }
    
        public virtual ICollection<QuestionnaireQCategory> QuestionnaireQCategories { get; set; }
        public virtual ICollection<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
    }
}
