//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireQuestion
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Ordinal { get; set; }
        public Nullable<int> QuestionnaireId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> QQCategoryId { get; set; }
    
        public virtual QuestionnaireQCategory QuestionnaireQCategory { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual Question Question { get; set; }
    }
}
