//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireQCategory
    {
        public QuestionnaireQCategory()
        {
            this.QuestionnaireQuestions = new HashSet<QuestionnaireQuestion>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> QuestionnaireId { get; set; }
        public Nullable<int> QCategoryId { get; set; }
        public int Ordinal { get; set; }
        public int SubOrdinal { get; set; }
    
        public virtual QCategory QCategory { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
    }
}
