//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public Respons()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ResponseId { get; set; }
        public int UserId { get; set; }
        public int QuestionnaireId { get; set; }
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public string QTitle { get; set; }
        public string QTypeResponse { get; set; }
        public int QuestionnaireQuestionId { get; set; }
        public int QQOrd { get; set; }
        public int QCategoryId { get; set; }
        public string QCategoryName { get; set; }
        public int Ordinal { get; set; }
        public int SubOrdinal { get; set; }
        public string ResponseItem { get; set; }
        public int QuestionnaireQCategoryId { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
