//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevel
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FinalStepLevel { get; set; }
        public Nullable<System.DateTime> FinalStepLevelDate { get; set; }
    }
}
