//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification
    {
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public int UserId { get; set; }
        public int QCategoryId { get; set; }
        public int SubOrdinal { get; set; }
        public string ItemInfo { get; set; }
        public bool ItemVerified { get; set; }
        public string ItemStepLevel { get; set; }
        public string Notes { get; set; }
        public bool Editable { get; set; }
        public int QQCategoryId { get; set; }
    }
}
